checkpoint_path: ./checkpoints/avgflow_52m_ckpt.pkl
output_dir: ./example/output
run_name: avgflow_52m

use_ema: true
solver: euler # tsit5 or euler
rtol: 1e-5 # only use when using tsit5 solver
atol: 1e-4 # only use when using tsit5 solver
only_save_last: false
n_steps: 100 # not use when using tsit5 solver
t_schedule: uniform # uniform or log
t_p: 2.0 # Not used for uniform t-schedule, only used for log t-schedule
featurize_mode: drugs # Featurization mode for model trained with GEOM-Drugs dataset
random_seed: 42

model:
  batchsize: 32 # Batch size for generation
  max_n: 200
  feat_dim: 75
  pe_dim: 32
  input_dim: 113 # 3+3+feat_dim+pe_dim
  node_dim: 512
  cond_dim: 512
  graph_feat_dim: 5
  n_edge_type: 5
  edge_type_emb_dim: 126 # 128-2
  n_heads: 8
  n_layers: 8
  n_registers: 10

flow_matcher:
  target_mode: avgflow
  loss_mode: ut
  self_cond: false
  learning_rate: 0.0001
  scale_lr_by_num_devices: false
  time_schedule: uniform
  learning_rate_scheduler:
    learning_rate: 0.0001 # default 0.0002
    init_value: 0.00001 # default 1e-6
    warmup_steps: 500 # default 10_000
    decay_steps: 1_000_000 # default 1_000_000
    end_value: 0.00001 # default 1e-6
