data_root_dir: /home/zhonglinc/storage/research/avgflow_release/dit_pairwise_bias/example/
data_file_name: reflow_toy_mols.pkl
# Define the checkpoint to finetune from
pretrained_ckpt: /home/zhonglinc/storage/research/dit_pairwise_bias/dit_pairwise_bias/test/dit_52M_avgflow/ep_760_ckpt.pkl
# Define where to save the finetuned checkpoint
checkpoint_dir: /home/zhonglinc/storage/research/avgflow_release/dit_pairwise_bias/example/checkpoints
run_name: 52m_toydata_finetune

model:
  batchsize: 4
  max_n: 200
  feat_dim: 75
  pe_dim: 32
  input_dim: 113 # 3+3+feat_dim+pe_dim
  node_dim: 512
  cond_dim: 512
  graph_feat_dim: 5
  n_edge_type: 5
  edge_type_emb_dim: 126 # 128-2
  n_heads: 8
  n_layers: 8
  n_registers: 10

flow_matcher:
  target_mode: linear # Attention: Using linear flow is needed for reflow finetuning
  loss_mode: ut
  self_cond: false
  learning_rate: 0.0001
  scale_lr_by_num_devices: false
  time_schedule: uniform # Attention: If distilling for 1-step generation, use 'distill' instead
  learning_rate_scheduler:
    learning_rate: 0.0001 # default 0.0002
    init_value: 0.00001 # default 1e-6
    warmup_steps: 500 # default 10_000
    decay_steps: 1_000_000 # default 1_000_000
    end_value: 0.00001 # default 1e-6

training:
  ema_beta: 0.001
  n_epochs: 600
  save_every_n_epoch: [500, 600]
  save_interval_change_threshold: [1000]
  log_every_n_step: 1

validation:
  val_every_n_epoch: 10
  n_val_samples: 4

wandb:
  use_wandb: True
  project: confgen
  entity: zhonglinc
